### ISSUE TITLE
Frequency Analysis

### ISSUE THREAD

**Issue by mevanekanayake** [xmindflow/INCODE#1]
This is a wonderful piece of work. Thank you! I am trying to understand the frequency analysis of the layers (Figure 2). Do you have the code for that experiment? Or else, could you explain how the activation spectrums were obtained for Fig. 2?

**Comment by amirhossein-kz** [comment]
Hi @mevanekanayake,
Thank you very much for your interest. Can you please share your email so I can send the code to you? I cannot upload it here.

**Comment by mevanekanayake** [comment]
You can send it to me at mevan dot ekanayake at monash dot edu. Thank you
so much.

**Comment by mevanekanayake** [comment]
Just following up on this. mevan.ekanayake@monash.edu
