### ISSUE TITLE
Confusion about the audio representation in Figure 8

### ISSUE THREAD

**Issue by lif314** [xmindflow/INCODE#2]
When using PE+ReLU to fit the audio, the network output layer passes through a sigmoid ([code](https://github.com/xmindflow/INCODE/blob/main/modules/relu.py#L95)), which means the output values are always within (0, 1). However, the audio amplitude is within (-1, 1), which will result in the complete loss of audio signals in the (-1, 0) range. Did you have any additional settings in your experiments?

**Comment by amirhossein-kz** [comment]
@lif314, Thank you so much for pointing that out. I included that code for image representation, but I originally did not use it for audio representation in my experiments. I'll fix it in the repo. Thanks!

**Comment by lif314** [comment]
> @lif314, Thank you so much for pointing that out. I included that code for image representation, but I originally did not use it for audio representation in my experiments. I'll fix it in the repo. Thanks!

Looking forward to it! I am also interested in issue [Frequency Analysis](https://github.com/xmindflow/INCODE/issues/1), could you also send a copy of the code to my email (cslinfeili@gmail.com)? Thank you very much!
